version: '3.8'
services:
  postgres:
    container_name: pg_container
    image: seungyeonha3/s624:pqsql1.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stat1234 
      POSTGRES_DATABASE: sqlda
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:8.2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - ./db_image/servers.json:/pgadmin4/servers.json
      - ./sql_scripts:/home/sql_scripts
      - ./my_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'postgres:5432:*:postgres:stat1234' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh" 
    depends_on:
      - postgres
  pynb:
    container_name: pynb_container
    image:  seungyeonha3/s624:pyn1.3
    user: root
    restart: always
    volumes:
      - ./jupyter_notebooks:/home/notebooks
    ports:
      - "8888:8888"
      - "8797:8797"
  Rstudio:
    container_name: Rstudio
    image: rst:latest
    restart: always
    environment:
      - USERNAME=rstudio
      - PASSWORD=rstudio
    volumes:
      - ./rstudio-server-data:/home/rstudio
    ports:
      - "8787:8787"
    working_dir: /home/rstudio
    entrypoint:
      - /usr/lib/rstudio-server/bin/rserver
    command:
      - --server-daemonize=0
      - --server-app-armor-enabled=0

volumes:
  sql_scripts:
  jupyter_notebooks:
  my_data:
  rstudio-server-data: 
    
